# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170113_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='tip',
            field=models.CharField(default='', max_length=200),
        ),
    ]
